language: objective-c
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
            - aviralg@ncbs.res.in
            - hrani@ncbs.res.in
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly

before_install:
    - brew update 
    - brew outdated xctool || brew upgrade xctool
    - brew install gsl
    - brew install homebrew/science/hdf5 
    - brew install python cmake 
    - brew install homebrew/python/numpy 
    - brew install homebrew/python/matplotlib
    - brew install pyqt
    - brew install openscenegraph

script:
    - make BUILD=debug USE_NEUROKIT=1 && make clean
    - mkdir -p _build && cd _build && cmake -DDEBUG=ON -DWITH_DOC=ON .. && make
    - ctest --output-on-failure
